const couponData = [
  {
    code: "SAVE10",
    description: "Get 10% off your next purchase.",
    discount_type: "percentage",
    discount_value: 10,
    start_date: "2024-01-01",
    end_date: "2024-01-31",
    is_active: true,
  },
  {
    code: "FREESHIP",
    description: "Free shipping on orders over $50.",
    discount_type: "fixed",
    discount_value: 0,
    start_date: "2024-02-01",
    end_date: "2024-02-28",
    is_active: true,
  },
  {
    code: "SUMMER20",
    description: "Enjoy 20% off summer collection.",
    discount_type: "percentage",
    discount_value: 20,
    start_date: "2024-03-01",
    end_date: "2024-03-31",
    is_active: true,
  },
  {
    code: "BLACKFRIDAY",
    description: "Black Friday Sale: $50 off any purchase.",
    discount_type: "fixed",
    discount_value: 50,
    start_date: "2024-11-24",
    end_date: "2024-11-30",
    is_active: true,
  },
  {
    code: "NEWYEAR15",
    description: "15% off to celebrate the New Year!",
    discount_type: "percentage",
    discount_value: 15,
    start_date: "2024-12-31",
    end_date: "2025-01-15",
    is_active: true,
  },
  {
    code: "WELCOME5",
    description: "Welcome coupon: $5 off your first order.",
    discount_type: "fixed",
    discount_value: 5,
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    is_active: true,
  },
  {
    code: "FLASHSALE",
    description: "Flash Sale: 30% off for the next 24 hours!",
    discount_type: "percentage",
    discount_value: 30,
    start_date: "2024-09-18",
    end_date: "2024-09-19",
    is_active: true,
  },
];

module.exports = couponData;
