const orderData = [
  {
    user_id: 12,
    billing_address_id: 1,
    shipping_address_id: 2,
    payment_method_id: 2,
    payment_status: "completed",
    order_status: "shipped",
    total_amount: 59.99,
  },
  {
    user_id: 3,
    billing_address_id: 3,
    shipping_address_id: 4,
    payment_method_id: 2,
    payment_status: "pending",
    order_status: "processing",
    total_amount: 66.0,
  },
  {
    user_id: 5,
    billing_address_id: 5,
    shipping_address_id: 5,
    payment_method_id: 1,
    payment_status: "failed",
    order_status: "pending",
    total_amount: 45.0,
  },
  {
    user_id: 15,
    billing_address_id: 6,
    shipping_address_id: 6,
    payment_method_id: 1,
    payment_status: "failed",
    order_status: "cancelled",
    total_amount: 120.0,
  },
  {
    user_id: 2,
    billing_address_id: 7,
    shipping_address_id: 7,
    payment_method_id: 5,
    payment_status: "refunded",
    order_status: "cancelled",
    total_amount: 75.75,
  },
  {
    user_id: 4,
    billing_address_id: 8,
    shipping_address_id: 8,
    payment_method_id: 5,
    payment_status: "failed",
    order_status: "cancelled",
    total_amount: 75.75,
  },
  {
    user_id: 11,
    billing_address_id: 9,
    shipping_address_id: 10,
    payment_method_id: 5,
    payment_status: "completed",
    order_status: "shipped",
    total_amount: 30.0,
  },
];

module.exports = orderData;
