const shippingAddresseData = [
  {
    user_id: 1,
    address_line_1: "123 Main St",
    address_line_2: "Apt 4B",
    city: "New York",
    state: "NY",
    country: "USA",
    postal_code: "10001",
  },
  {
    user_id: 2,
    address_line_1: "456 Maple Ave",
    address_line_2: "",
    city: "Los Angeles",
    state: "CA",
    country: "USA",
    postal_code: "90001",
  },
  {
    user_id: 3,
    address_line_1: "789 Oak St",
    address_line_2: "Suite 300",
    city: "Chicago",
    state: "IL",
    country: "USA",
    postal_code: "60601",
  },
  {
    user_id: 4,
    address_line_1: "101 Pine Rd",
    address_line_2: "",
    city: "Houston",
    state: "TX",
    country: "USA",
    postal_code: "77001",
  },
  {
    user_id: 5,
    address_line_1: "202 Birch Blvd",
    address_line_2: "Floor 2",
    city: "Phoenix",
    state: "AZ",
    country: "USA",
    postal_code: "85001",
  },
  {
    user_id: 6,
    address_line_1: "303 Cedar St",
    address_line_2: "",
    city: "Philadelphia",
    state: "PA",
    country: "USA",
    postal_code: "19101",
  },
  {
    user_id: 7,
    address_line_1: "404 Elm St",
    address_line_2: "Unit 5A",
    city: "San Antonio",
    state: "TX",
    country: "USA",
    postal_code: "78201",
  },
  {
    user_id: 8,
    address_line_1: "505 Spruce St",
    address_line_2: "",
    city: "San Diego",
    state: "CA",
    country: "USA",
    postal_code: "92101",
  },
  {
    user_id: 9,
    address_line_1: "606 Walnut St",
    address_line_2: "Box 7",
    city: "Dallas",
    state: "TX",
    country: "USA",
    postal_code: "75201",
  },
  {
    user_id: 10,
    address_line_1: "707 Fir St",
    address_line_2: "",
    city: "San Jose",
    state: "CA",
    country: "USA",
    postal_code: "95101",
  },
];

module.exports = shippingAddresseData;
