const sizeData = [
  { size: 1 },
  { size: 2 },
  { size: 3 },
  { size: 4 },
  { size: 5 },
  { size: 6 },
  { size: 7  },
  { size: 8 },
  { size: 9 },
  { size: 10 },
  { size: 11 },
  { size: 35 },
  { size: 36 },
  { size: 37 },
  { size: 38 },
  { size: 39 },
  { size: 40 },
  { size: 41 },
  { size: 42 },
  { size: 43 },
  { size: 44 },
];

module.exports = sizeData;
